# Example on Makefile

edit: main.o kdb.o command.o display.o insert.o search.o \
	files.o utils.o
	cc -o edit main.o kdb.o command.o display.o insert.o search.o files.o utils.o
mian.o: main.c defs.h
	cc -c main.c
kdb.o: kdb.c defs.h command.h
	cc -c kdb.c
command.o: command.c defs.h command.h
	cc -c command.c
display.o: display.c defs.h buffer.h
	cc -c display.c
insert.o: insert.c defs.h buffer.h
	cc -c insert.c
search.o: search.c defs.h buffer.h
	cc -c search.c
files.o: files.c defs.h buffer.h command.h
	cc -c files.c
utils.o: utils.c defs.h
	cc -c utils.c
clean:
	rm edit main.o kdb.o command.o display.o insert.o search.o files.o utils.o
