
contents := $(shell cat foo)
files := $(shell echo *file)
test:
	echo $(patsubst %.c, %.o, x.c c.c bar.c y.c.c )
	echo $(patsubst <pattern>, <replacement>, $(var))
	echo -n "$(contents)\n"
	echo $(files)
	# Please be familiar the basic usage of Makefiles.
	$(warning exiting due to error)
	$(error exiting due to error)






